[Exercise 1] add tests #10
Theomat/software-engineering-enseirb-2020 pull request #18
Opened 2020-11-11 19:04 UTC by Theomat

2020-11-11 19:10 UTC, Galeniium commented on exercice1/test_exo1.py
> +    assert cm.shape == (8, 8)
La vérification est arbitraire, changer pour une shape de taille dépendante de nombre catégories.

2020-11-11 20:00 UTC, Theomat commented
The tests did not pass for the endpoint tested is ```localhost:8080``` we either need to change that to the AWS endpoint or manage to run the docker image on github actions

2020-11-12 10:18 UTC, otaviojacobi requested changes

2020-11-12 10:18 UTC, otaviojacobi commented on exercice1/test_exo1.py
> +    assert cm.shape == (8, 8)
Je suis d'accord avec @Galeniium

2020-11-12 10:36 UTC, otaviojacobi approved these changes

2020-11-12 10:36 UTC, merged